frd_user:
    resource: "@FRDUserBundle/Controller/"
    type:     annotation
    prefix:   /

frd_car:
    resource: "@FRDCarBundle/Controller/"
    type:     annotation
    prefix:   /cars/

frd_produto:
    resource: "@FRDProdutoBundle/Controller/"
    type:     annotation
    prefix:   /produtos/

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
